--------------------------------------------------------
--  File created - Friday-August-28-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table GRADEBOOK_REVISITED
--------------------------------------------------------

  CREATE TABLE "TESTDB"."GRADEBOOK_REVISITED" 
   (	"STUDENTID" NUMBER, 
	"ASSIGNMENT" VARCHAR2(255 BYTE), 
	"TYPE" VARCHAR2(50 BYTE), 
	"CLASSID" VARCHAR2(50 BYTE), 
	"SUBMISSION_DATE" DATE, 
	"GRADE" NUMBER, 
	"GPA" NUMBER(10,3)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into TESTDB.GRADEBOOK_REVISITED
SET DEFINE OFF;
Insert into TESTDB.GRADEBOOK_REVISITED (STUDENTID,ASSIGNMENT,TYPE,CLASSID,SUBMISSION_DATE,GRADE,GPA) values (123456,'fdgfd','quiz','1',to_date('12-FEB-15','DD-MON-RR'),88,44);
Insert into TESTDB.GRADEBOOK_REVISITED (STUDENTID,ASSIGNMENT,TYPE,CLASSID,SUBMISSION_DATE,GRADE,GPA) values (123456,'dsgfd','test','202',to_date('03-JAN-15','DD-MON-RR'),150,107);
Insert into TESTDB.GRADEBOOK_REVISITED (STUDENTID,ASSIGNMENT,TYPE,CLASSID,SUBMISSION_DATE,GRADE,GPA) values (123456,'fdsgdf','Project','202',to_date('06-JAN-15','DD-MON-RR'),90,107);
Insert into TESTDB.GRADEBOOK_REVISITED (STUDENTID,ASSIGNMENT,TYPE,CLASSID,SUBMISSION_DATE,GRADE,GPA) values (123456,'nhcgjh','quiz','202',to_date('02-JAN-15','DD-MON-RR'),100,107);
Insert into TESTDB.GRADEBOOK_REVISITED (STUDENTID,ASSIGNMENT,TYPE,CLASSID,SUBMISSION_DATE,GRADE,GPA) values (123456,'fhdjfhgj','quiz','202',to_date('02-JAN-15','DD-MON-RR'),50,107);
Insert into TESTDB.GRADEBOOK_REVISITED (STUDENTID,ASSIGNMENT,TYPE,CLASSID,SUBMISSION_DATE,GRADE,GPA) values (123456,'fdsf','quiz','101',to_date('02-JAN-15','DD-MON-RR'),100,20);
Insert into TESTDB.GRADEBOOK_REVISITED (STUDENTID,ASSIGNMENT,TYPE,CLASSID,SUBMISSION_DATE,GRADE,GPA) values (123456,'fdsfgd','test','101',to_date('05-JAN-15','DD-MON-RR'),50,20);
Insert into TESTDB.GRADEBOOK_REVISITED (STUDENTID,ASSIGNMENT,TYPE,CLASSID,SUBMISSION_DATE,GRADE,GPA) values (123456,'nhcgjh','quiz','202',to_date('02-JAN-15','DD-MON-RR'),100,0);
Insert into TESTDB.GRADEBOOK_REVISITED (STUDENTID,ASSIGNMENT,TYPE,CLASSID,SUBMISSION_DATE,GRADE,GPA) values (123456,'hdfsjkhgj','homework','1',to_date('20-JAN-15','DD-MON-RR'),90,44);
Insert into TESTDB.GRADEBOOK_REVISITED (STUDENTID,ASSIGNMENT,TYPE,CLASSID,SUBMISSION_DATE,GRADE,GPA) values (123456,'fgmhfhdg','project','1',to_date('02-MAR-15','DD-MON-RR'),50,44);
Insert into TESTDB.GRADEBOOK_REVISITED (STUDENTID,ASSIGNMENT,TYPE,CLASSID,SUBMISSION_DATE,GRADE,GPA) values (123456,'fdm,gj','test','1',to_date('02-JAN-15','DD-MON-RR'),10,44);
Insert into TESTDB.GRADEBOOK_REVISITED (STUDENTID,ASSIGNMENT,TYPE,CLASSID,SUBMISSION_DATE,GRADE,GPA) values (123456,'bgfnbgf','quiz','202',to_date('03-JAN-15','DD-MON-RR'),200,107);
